language: php

php:
  - 5.6

services:
  - mysql

mysql:
  database: 36000
  username: root
  encoding: utf8

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Update composer
before-install:
  - composer self-update

install:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - echo "sbnet_weather.owm.key: none" >> app/config/parameters.yml
  - echo "sbnet_weather.wc.key: none" >> app/config/parameters.yml
  - composer install
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:update --force
  - php bin/console doctrine:fixtures:load -n

script:
  - phpunit
