language: php
php:
  - 5.6
  - 7.0
  - hhvm

install:
  - composer install 

mysql:
  database: 36000
  username: root
  encoding: utf8

before_script:
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:update --force
  - php bin/console doctrine:fixtures:load -n