sbnet_front_homepage:
    path:     /
    defaults: { _controller: SbnetFrontBundle:Default:index }

sbnet_front_search:
    path:     /search
    defaults: { _controller: SbnetFrontBundle:Default:search }

sbnet_front_city:
    path:     /city/{id}-{post_code}-{name}
    defaults: { _controller: SbnetFrontBundle:Default:city }

sbnet_front_region:
    path:     /region/{id}-{name}
    defaults: { _controller: SbnetFrontBundle:Default:region }

sbnet_front_area:
    path:     /area/{id}-{name}
    defaults: { _controller: SbnetFrontBundle:Default:area }
