services:
    sbnet_front.apiaccess:
        class: Sbnet\FrontBundle\ApiAccess\ApiAccess
        arguments:
          - "@circle.restclient"
          #- http://localhost:3000/
          - http://api.36000.fr/
