services:
    sbnet_front.apiaccess:
        class: Sbnet\FrontBundle\ApiAccess\ApiAccess
        arguments:
          - "@circle.restclient"
          - http://api.36000.fr
          #- %sbnet_front.apiaccess.url%
